---
version: "2"
services:

 devel:
  build:
   context: .
   dockerfile: dockerfile-build
  volumes:
   - webapps:/root/example-tomcat-war/target/

 prod:
  image: tomcat:8.0
  volumes:
   - webapps:/usr/local/tomcat/webapps/
  ports:
   - 8080:8080
  links:
   - devel
  depends_on:
   - devel

volumes:
 webapps:
