---
version: "3"
services:

 devel:
  build:
   context: .
   dockerfile: dockerfile-build
   links:
    - prod
   volumes:
    - /root/storage:/root/example-tomcat-war/target

  prod:
   build:
    context: .
    dockerfile: dockerfile-prod
    links:
     - devel
    volumes:
     - /root/storage:/usr/local/tomcat/webapps
    ports:
     - "8080:8080"
