---
version: "2"
services:

 devel:
  build:
   context: .
   dockerfile: dockerfile-build
  volumes:
   - /root/storage:/root/example-tomcat-war/target

 prod:
  build:
   context: .
   dockerfile: dockerfile-prod
  volumes:
   - /root/storage:/usr/local/tomcat/webapps
  volumes_from:
   - devel
  ports:
   - "8080:8080"
