FROM ubuntu:16.04 
RUN apt-get update && apt install -y git maven nginx 
WORKDIR /root 
RUN git clone https://github.com/doct15/example-tomcat-war.git 
WORKDIR /root/example-tomcat-war 
RUN mvn package
CMD ["nginx", "-g", "daemon off;"]
